[package]
name = "rcl_line"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.3.0"
cosmwasm-schema = "1.3.0"
cosmwasm-storage = "1.3.0"
cw2 = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
