[workspace]
resolver = "2"
members = [
  "contracts/bond_factory",
  "contracts/bond_series",
  "packages/heb-types",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://example.invalid/heb"
